// Generated by CoffeeScript 2.7.0
// exceptions.test.coffee
var block, norm, snorm;

import test from 'ava';

import {
  haltOnError,
  logErrors,
  LOG,
  DEBUG,
  error,
  assert,
  croak,
  normalize,
  super_normalize
} from '@jdeighan/exceptions';

// ---------------------------------------------------------------------------
test('foo', (t) => {
  return t.pass();
});

block = `abc\tdef
\tabc     def`;

norm = normalize(block);

snorm = super_normalize(block);

test('normalize', (t) => {
  return t.is(norm, "abc def\nabc def");
});

test('super_normalize', (t) => {
  return t.is(snorm, "abc def abc def");
});
