// Generated by CoffeeScript 2.7.0
// stack.test.coffee
import test from 'ava';

import {
  pass,
  undef
} from '@jdeighan/exceptions/utils';

import {
  CallStack
} from '@jdeighan/exceptions/stack';

// ---------------------------------------------------------------------------
test("line 10", (t) => {
  var stack;
  stack = new CallStack();
  return t.is(stack.getLevel(), 0);
});

test("line 14", (t) => {
  var stack;
  stack = new CallStack();
  return t.is(stack.isLogging(), false);
});

// .............................................................
test("line 20", (t) => {
  var stack;
  stack = new CallStack();
  stack.enter('callme', undef, [1, 'abc'], true);
  return t.is(stack.getLevel(), 1);
});

test("line 25", (t) => {
  var stack;
  stack = new CallStack();
  stack.enter('callme', undef, [1, 'abc'], true);
  return t.is(stack.isLogging(), true);
});

// .............................................................
test("line 32", (t) => {
  var stack;
  stack = new CallStack();
  stack.enter('sub', undef, [], false);
  return t.is(stack.getLevel(), 0);
});

test("line 37", (t) => {
  var stack;
  stack = new CallStack();
  stack.enter('sub', undef, [], true);
  return t.is(stack.getLevel(), 1);
});

test("line 42", (t) => {
  var stack;
  stack = new CallStack();
  stack.enter('sub', undef, [], false);
  return t.is(stack.isLogging(), false);
});

// .............................................................
test("line 49", (t) => {
  var stack;
  stack = new CallStack();
  stack.enter('callme', undef, [1, 'abc'], true);
  stack.enter('sub', undef, [], false);
  stack.returnFrom('sub', undef);
  return t.is(stack.getLevel(), 1);
});

test("line 56", (t) => {
  var stack;
  stack = new CallStack();
  stack.enter('callme', undef, [1, 'abc'], true);
  stack.enter('sub', undef, [], false);
  stack.returnFrom('sub', undef);
  return t.is(stack.isLogging(), true);
});
