// Generated by CoffeeScript 2.7.0
// taml.test.coffee
import test from 'ava';

import {
  assert,
  croak
} from '@jdeighan/exceptions';

import {
  undef,
  untabify
} from '@jdeighan/exceptions/utils';

import {
  LOG
} from '@jdeighan/exceptions/log';

import {
  isTAML,
  toTAML,
  fromTAML
} from '@jdeighan/exceptions/taml';

// ---------------------------------------------------------------------------
test("line 12", (t) => {
  return t.truthy(isTAML("---\n- first\n- second"));
});

test("line 13", (t) => {
  return t.falsy(isTAML("x---\n5"));
});

test("line 14", (t) => {
  return t.falsy(isTAML("---x\n5"));
});

test("line 16", (t) => {
  return t.is(toTAML({
    a: 1
  }), "---\na: 1");
});

test("line 17", (t) => {
  return t.is(toTAML({
    a: 1,
    b: 2
  }), "---\na: 1\nb: 2");
});

test("line 18", (t) => {
  return t.is(toTAML([
    1,
    'abc',
    {
      a: 1
    }
  ]), "---\n- 1\n- abc\n-\n   a: 1");
});

test("line 21", (t) => {
  return t.is(toTAML({
    a: 1,
    b: 2
  }), `---
a: 1
b: 2`);
});

test("line 27", (t) => {
  return t.is(toTAML(['a', 'b']), `---
- a
- b`);
});

test("line 33", (t) => {
  return t.is(toTAML([
    'a',
    'b',
    {
      a: 1
    },
    ['x']
  ]), untabify(`---
- a
- b
-
	a: 1
-
	- x`));
});

test("line 43", (t) => {
  return t.deepEqual(fromTAML("---\n- a\n- b"), ['a', 'b']);
});

test("line 44", (t) => {
  return t.deepEqual(fromTAML(`---
title:
\ten: Hello, she said.`), {
    title: {
      en: 'Hello, she said.'
    }
  });
});

test("line 62", (t) => {
  return t.deepEqual(fromTAML(`---
a: 1
b: 2`), {
    a: 1,
    b: 2
  });
});

test("line 46", (t) => {
  return t.is(toTAML(undef), "---\nundef");
});

test("line 47", (t) => {
  return t.is(toTAML(null), "---\nnull");
});

test("line 48", (t) => {
  return t.is(toTAML({
    a: 1
  }), "---\na: 1");
});

test("line 49", (t) => {
  return t.is(toTAML({
    a: 1,
    b: 2
  }), "---\na: 1\nb: 2");
});

test("line 50", (t) => {
  return t.is(toTAML([
    1,
    'abc',
    {
      a: 1
    }
  ]), "---\n- 1\n- abc\n-\n   a: 1");
});

test("line 52", (t) => {
  return t.is(toTAML({
    a: 1,
    b: 2
  }), `---
a: 1
b: 2`);
});

test("line 58", (t) => {
  return t.is(toTAML(['a', 'b']), `---
- a
- b`);
});

test("line 64", (t) => {
  return t.is(toTAML([
    'a',
    'b',
    {
      a: 1
    },
    ['x']
  ]), untabify(`---
- a
- b
-
	a: 1
-
	- x`));
});

test("line 74", (t) => {
  return t.is(toTAML(['xyz', 42, false, 'false', undef]), `---
- xyz
- 42
- false
- 'false'
- undef`);
});
