// Generated by CoffeeScript 2.7.0
// tamlFix.test.coffee
import test from 'ava';

import {
  assert,
  croak
} from '@jdeighan/exceptions';

import {
  undef
} from '@jdeighan/exceptions/utils';

import {
  LOG
} from '@jdeighan/exceptions/log';

import {
  tamlFix,
  fixValStr
} from '@jdeighan/exceptions/taml';

// ---------------------------------------------------------------------------
test("line 12", (t) => {
  return t.is(fixValStr(""), "");
});

test("line 15", (t) => {
  return t.is(fixValStr("5"), "5");
});

test("line 18", (t) => {
  return t.is(fixValStr("'abc'"), "'abc'");
});

test("line 21", (t) => {
  return t.is(fixValStr('"5"'), '"5"');
});

test("line 24", (t) => {
  return t.is(fixValStr('abc'), "'abc'");
});

test("line 27", (t) => {
  return t.is(fixValStr("ab'cd"), "'ab''cd'");
});
