// Generated by CoffeeScript 2.7.0
// temp.coffee
var func, i, len, ref, result, type, x;

import {
  isClass,
  isConstructor,
  OL,
  jsType
} from '@jdeighan/base-utils';

func = function(x) {
  return 42;
};

ref = [
  func,
  42,
  'abc',
  {
    a: 13
  }
];
for (i = 0, len = ref.length; i < len; i++) {
  x = ref[i];
  console.log();
  console.log(`x = ${OL(x)}`);
  type = jsType(x);
  console.log(`jsType() returned ${OL(type)}`);
  result = isClass(func);
  console.log(`isClass() returned ${result}`);
  result = isConstructor(func);
  console.log(`isConstructor() returned ${result}`);
}
