// Generated by CoffeeScript 2.7.0
(function() {
  // temp.coffee
  var i, lStrings, len, str;

  lStrings = ["abc  ", "def\t\t"];

  for (i = 0, len = lStrings.length; i < len; i++) {
    str = lStrings[i];
    str = str.trim();
  }

  console.log(lStrings);

}).call(this);
