// Generated by CoffeeScript 2.7.0
// debug.coffee
var dbgReturnVal, dbgYieldFrom, internalDebugging, lFuncList, logAll, logEnter, logResume, logReturn, logString, logType, logValue, logYield;

import {
  assert,
  croak
} from '@jdeighan/base-utils/exceptions';

import {
  undef,
  defined,
  notdefined,
  OL,
  OLS,
  isIdentifier,
  isFunctionName,
  isString,
  isFunction,
  isArray,
  isHash,
  isBoolean,
  isInteger,
  isEmpty,
  nonEmpty,
  arrayToBlock,
  getOptions,
  words,
  firstWord,
  inList,
  oneof
} from '@jdeighan/base-utils/utils';

import {
  getPrefix
} from '@jdeighan/base-utils/prefix';

import {
  LOG,
  LOGVALUE,
  stringFits,
  debugLogging,
  getMyLog
} from '@jdeighan/base-utils/log';

import {
  toTAML
} from '@jdeighan/base-utils/taml';

import {
  CallStack
} from '@jdeighan/base-utils/stack';

export {
  debugLogging
};

export var callStack = new CallStack();

lFuncList = []; // array of {funcName, plus}

logAll = false; // if true, always log

internalDebugging = false;

// --- Custom loggers, if defined
logEnter = undef;

logReturn = undef;

logYield = undef;

logResume = undef;

logString = undef;

logValue = undef;

// ---------------------------------------------------------------------------
export var getDebugLog = () => {
  return getMyLog();
};

// ---------------------------------------------------------------------------
export var setCallStack = function(hOptions = {}) {
  callStack = new CallStack(getOptions(hOptions));
};

// ---------------------------------------------------------------------------
export var debugDebug = (debugFlag = true) => {
  internalDebugging = debugFlag;
};

// ---------------------------------------------------------------------------
export var dumpDebugLoggers = function(label = undef) {
  var lLines;
  lLines = [];
  if (nonEmpty(label)) {
    lLines.push(`LOGGERS (${label})`);
  } else {
    lLines.push("LOGGERS");
  }
  lLines.push(`   enter      - ${logType(logEnter, stdLogEnter)}`);
  lLines.push(`   return     - ${logType(logReturn, stdLogReturn)}`);
  lLines.push(`   yield      - ${logType(logYield, stdLogYield)}`);
  lLines.push(`   resume     - ${logType(logResume, stdLogResume)}`);
  lLines.push(`   string     - ${logType(logString, stdLogString)}`);
  lLines.push(`   value      - ${logType(logValue, stdLogValue)}`);
  return console.log(arrayToBlock(lLines));
};

// ---------------------------------------------------------------------------
logType = function(cur, std) {
  if (cur === std) {
    return 'std';
  } else if (defined(cur)) {
    return 'custom';
  } else {
    return 'undef';
  }
};

// ---------------------------------------------------------------------------
export var setDebugging = function(...lParms) {
  var customSet, i, j, key, len, parm, value;
  // --- pass a hash to set custom loggers
  if (internalDebugging) {
    console.log(`setDebugging() with ${lParms.length} parms`);
  }
  callStack.reset();
  lFuncList = [];
  logAll = false;
  logEnter = stdLogEnter;
  logReturn = stdLogReturn;
  logYield = stdLogYield;
  logResume = stdLogResume;
  logString = stdLogString;
  logValue = stdLogValue;
  customSet = false;
  for (i = j = 0, len = lParms.length; j < len; i = ++j) {
    parm = lParms[i];
    if (isBoolean(parm)) {
      logAll = parm;
    } else if (isString(parm)) {
      logAll = false;
      if (internalDebugging) {
        console.log(`lParms[${i}] is string ${OL(parm)}`);
      }
      lFuncList = lFuncList.concat(getFuncList(parm));
    } else if (isHash(parm)) {
      if (internalDebugging) {
        console.log(`lParms[${i}] is hash ${OL(parm)}`);
      }
      customSet = true;
      for (key in parm) {
        value = parm[key];
        setCustomDebugLogger(key, value);
      }
    } else {
      croak(`Invalid parm to setDebugging(): ${OL(parm)}`);
    }
  }
  if (internalDebugging) {
    console.log('lFuncList:');
    console.log(toTAML(lFuncList));
    if (customSet) {
      dumpDebugLoggers();
    }
  }
};

// ---------------------------------------------------------------------------
export var setCustomDebugLogger = function(type, func) {
  assert(isFunction(func), "Not a function");
  switch (type) {
    case 'enter':
      logEnter = func;
      break;
    case 'returnFrom':
      logReturn = func;
      break;
    case 'yield':
      logYield = func;
      break;
    case 'resume':
      logResume = func;
      break;
    case 'string':
      logString = func;
      break;
    case 'value':
      logValue = func;
      break;
    default:
      throw new Error(`Unknown type: ${OL(type)}`);
  }
};

// ---------------------------------------------------------------------------
export var getFuncList = function(str) {
  var fullName, j, lFuncs, len, modifier, ref, word;
  lFuncs = [];
  ref = words(str);
  for (j = 0, len = ref.length; j < len; j++) {
    word = ref[j];
    if (word === 'debug') {
      internalDebugging = true;
    }
    [fullName, modifier] = parseFunc(word);
    assert(defined(fullName), `Bad debug object: ${OL(word)}`);
    lFuncs.push({
      fullName,
      plus: modifier === '+'
    });
  }
  return lFuncs;
};

// ---------------------------------------------------------------------------
// Stack is only modified in these 8 functions (it is reset in setDebugging())
// ---------------------------------------------------------------------------
export var dbgEnter = function(funcName, ...lValues) {
  var doLog, level;
  assert(isFunctionName(funcName), "not a valid function name");
  doLog = logAll || funcMatch(funcName);
  if (internalDebugging) {
    if (lValues.length === 0) {
      console.log(`dbgEnter ${OL(funcName)}`);
    } else {
      console.log(`dbgEnter ${OL(funcName)}, ${OLS(lValues)}`);
    }
    console.log(`   - doLog = ${OL(doLog)}`);
  }
  if (doLog) {
    level = callStack.logLevel;
    if (!logEnter(level, funcName, lValues)) {
      stdLogEnter(level, funcName, lValues);
    }
  }
  callStack.enter(funcName, lValues, doLog);
  return true;
};

// ---------------------------------------------------------------------------
export var dbgReturn = function(...lArgs) {
  var doLog, funcName, level;
  if (lArgs.length > 1) {
    return dbgReturnVal(...lArgs);
  }
  funcName = lArgs[0];
  assert(isFunctionName(funcName), "not a valid function name");
  doLog = logAll || callStack.isLogging();
  if (internalDebugging) {
    console.log(`dbgReturn ${OL(funcName)}`);
    console.log(`   - doLog = ${OL(doLog)}`);
  }
  if (doLog) {
    level = callStack.logLevel;
    if (!logReturn(level, funcName)) {
      stdLogReturn(level, funcName);
    }
  }
  callStack.returnFrom(funcName);
  return true;
};

// ---------------------------------------------------------------------------
dbgReturnVal = function(funcName, val) {
  var doLog, level;
  assert(isFunctionName(funcName), "not a valid function name");
  doLog = logAll || callStack.isLogging();
  if (internalDebugging) {
    console.log(`dbgReturn ${OL(funcName)}, ${OL(val)}`);
    console.log(`   - doLog = ${OL(doLog)}`);
  }
  if (doLog) {
    level = callStack.logLevel;
    if (!logReturn(level, funcName, val)) {
      stdLogReturn(level, funcName, val);
    }
  }
  callStack.returnFrom(funcName, val);
  return true;
};

// ---------------------------------------------------------------------------
export var dbgYield = function(...lArgs) {
  var doLog, funcName, level, nArgs, val;
  nArgs = lArgs.length;
  assert((nArgs === 1) || (nArgs === 2), `Bad num args: ${nArgs}`);
  [funcName, val] = lArgs;
  if (nArgs === 1) {
    return dbgYieldFrom(funcName);
  }
  assert(isFunctionName(funcName), "not a function name");
  doLog = logAll || callStack.isLogging();
  if (internalDebugging) {
    console.log(`dbgYield ${OL(funcName)} ${OL(val)}`);
    console.log(`   - doLog = ${OL(doLog)}`);
  }
  if (doLog) {
    level = callStack.logLevel;
    if (!logYield(level, funcName, val)) {
      stdLogYield(level, funcName, val);
    }
  }
  callStack.yield(funcName, val);
  return true;
};

// ---------------------------------------------------------------------------
dbgYieldFrom = function(funcName) {
  var doLog, level;
  assert(isFunctionName(funcName), "not a function name");
  doLog = logAll || callStack.isLogging();
  if (internalDebugging) {
    console.log(`dbgYieldFrom ${OL(funcName)}`);
    console.log(`   - doLog = ${OL(doLog)}`);
  }
  if (doLog) {
    level = callStack.logLevel;
    if (!logYieldFrom(level, funcName)) {
      stdLogYieldFrom(level, funcName);
    }
  }
  callStack.yield(funcName);
  return true;
};

// ---------------------------------------------------------------------------
export var dbgResume = function(funcName) {
  var doLog, level;
  assert(isFunctionName(funcName), "not a valid function name");
  doLog = logAll || callStack.isLogging();
  if (internalDebugging) {
    console.log(`dbgResume ${OL(funcName)}`);
    console.log(`   - doLog = ${OL(doLog)}`);
  }
  if (doLog) {
    level = callStack.logLevel;
    if (!logResume(funcName, level)) {
      stdLogResume(funcName, level);
    }
  }
  callStack.resume(funcName);
  return true;
};

// ---------------------------------------------------------------------------
export var dbgValue = function(label, val) {
  var doLog, level;
  assert(isString(label), "not a string");
  doLog = logAll || callStack.isLogging();
  if (internalDebugging) {
    console.log(`dbgValue ${OL(label)}, ${OL(val)}`);
    console.log(`   - doLog = ${OL(doLog)}`);
  }
  if (doLog) {
    level = callStack.logLevel;
    if (!logValue(level, label, val)) {
      stdLogValue(level, label, val);
    }
  }
  return true;
};

// ---------------------------------------------------------------------------
export var dbgString = function(str) {
  var doLog, level;
  assert(isString(str), "not a string");
  doLog = logAll || callStack.isLogging();
  if (internalDebugging) {
    console.log(`dbgString(${OL(str)})`);
    console.log(`   - doLog = ${OL(doLog)}`);
  }
  if (doLog) {
    level = callStack.logLevel;
    if (!logString(level, str)) {
      stdLogString(level, str);
    }
  }
  return true;
};

// ---------------------------------------------------------------------------
export var dbg = function(...lArgs) {
  if (lArgs.length === 1) {
    return dbgString(lArgs[0]);
  } else {
    return dbgValue(lArgs[0], lArgs[1]);
  }
};

// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
//    Only these 8 functions ever call LOG or LOGVALUE
export var stdLogEnter = function(level, funcName, lArgs) {
  var arg, i, idPre, itemPre, j, labelPre, len, str;
  assert(isFunctionName(funcName), "bad function name");
  assert(isArray(lArgs), "not an array");
  assert(isInteger(level), "level not an integer");
  labelPre = getPrefix(level, 'plain');
  if (lArgs.length === 0) {
    LOG(`enter ${funcName}`, labelPre);
  } else {
    str = `enter ${funcName} ${OLS(lArgs)}`;
    if (stringFits(`${labelPre}${str}`)) {
      LOG(str, labelPre);
    } else {
      idPre = getPrefix(level + 1, 'plain');
      itemPre = getPrefix(level + 2, 'dotLast2Vbars');
      LOG(`enter ${funcName}`, labelPre);
      for (i = j = 0, len = lArgs.length; j < len; i = ++j) {
        arg = lArgs[i];
        LOGVALUE(`arg[${i}]`, arg, idPre, itemPre);
      }
    }
  }
  return true;
};

// ---------------------------------------------------------------------------
export var stdLogReturn = function(...lArgs) {
  var funcName, labelPre, level, val;
  [level, funcName, val] = lArgs;
  if (lArgs.length === 3) {
    return stdLogReturnVal(level, funcName, val);
  }
  assert(isFunctionName(funcName), "bad function name");
  assert(isInteger(level), "level not an integer");
  labelPre = getPrefix(level, 'withArrow');
  LOG(`return from ${funcName}`, labelPre);
  return true;
};

// ---------------------------------------------------------------------------
export var stdLogReturnVal = function(level, funcName, val) {
  var idPre, itemPre, labelPre, str;
  assert(isFunctionName(funcName), "bad function name");
  assert(isInteger(level), "level not an integer");
  labelPre = getPrefix(level, 'withArrow');
  str = `return ${OL(val)} from ${funcName}`;
  if (stringFits(str)) {
    LOG(str, labelPre);
  } else {
    idPre = getPrefix(level, 'noLastVbar');
    itemPre = getPrefix(level, 'noLast2Vbars');
    LOG(`return from ${funcName}`, labelPre);
    LOGVALUE("val", val, idPre, itemPre);
  }
  return true;
};

// ---------------------------------------------------------------------------
export var stdLogYield = function(...lArgs) {
  var funcName, idPre, itemPre, labelPre, level, str, val, valStr;
  [level, funcName, val] = lArgs;
  if (lArgs.length === 2) {
    return stdLogYieldFrom(level, funcName);
  }
  labelPre = getPrefix(level, 'withFlat');
  valStr = OL(val);
  str = `yield ${valStr}`;
  if (stringFits(str)) {
    LOG(str, labelPre);
  } else {
    idPre = getPrefix(level + 1, 'plain');
    itemPre = getPrefix(level + 2, 'dotLast2Vbars');
    LOG("yield", labelPre);
    LOGVALUE("val", val, idPre, itemPre);
  }
  return true;
};

// ---------------------------------------------------------------------------
export var stdLogYieldFrom = function(level, funcName) {
  var labelPre;
  labelPre = getPrefix(level, 'withFlat');
  LOG("yieldFrom", labelPre);
  return true;
};

// ---------------------------------------------------------------------------
export var stdLogResume = function(funcName, level) {
  var labelPre;
  assert(isInteger(level), "level not an integer");
  labelPre = getPrefix(level, 'plain');
  // LOG "resume", labelPre  # no need to log it
  return true;
};

// ---------------------------------------------------------------------------
export var stdLogString = function(level, str) {
  var labelPre;
  assert(isString(str), "not a string");
  assert(isInteger(level), "level not an integer");
  labelPre = getPrefix(level, 'plain');
  LOG(str, labelPre);
  return true;
};

// ---------------------------------------------------------------------------
export var stdLogValue = function(level, label, val) {
  var labelPre;
  assert(isInteger(level), "level not an integer");
  labelPre = getPrefix(level, 'plain');
  LOGVALUE(label, val, labelPre);
  return true;
};

// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
export var getType = function(label, lValues = []) {
  var lMatches;
  // --- returns [type, funcName]
  //     <type> is one of:
  //        'enter'      - funcName is set
  //        'returnFrom' - funcName is set
  //        'yield'      - funcName is set
  //        'resume'     - funcName is set
  //        'string'     - funcName is undef
  //        'value'      - funcName is undef
  if (lMatches = label.match(/^(enter|yield|resume)\s+([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)(?:\(\))?$/)) {
    return [lMatches[1], lMatches[2]];
  }
  if (lMatches = label.match(/^return\s+from\s+([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)(?:\(\))?$/)) {
    return ['returnFrom', lMatches[1]];
  }
  // --- Check for deprecated forms
  assert(!oneof(firstWord(label), 'enter', 'returnFrom', 'yield', 'resume'), `deprecated form for debug(): ${OL(label)}`);
  // --- if none of the above returned, then...
  if (lValues.length === 1) {
    return ['value', undef];
  } else if (lValues.length === 0) {
    return ['string', undef];
  } else {
    throw new Error("More than 1 object not allowed here");
  }
};

// ---------------------------------------------------------------------------
export var funcMatch = function(fullName) {
  var h, j, len;
// --- fullName came from a call to dbgEnter()
  for (j = 0, len = lFuncList.length; j < len; j++) {
    h = lFuncList[j];
    if (h.fullName === fullName) {
      return true;
    }
    if (h.plus && callStack.isActive(fullName)) {
      return true;
    }
  }
  return false;
};

// ........................................................................
export var parseFunc = function(str) {
  var _, fullName, lMatches, modifier;
  // --- returns [fullName, modifier]
  if (lMatches = str.match(/^([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)(\+)?$/)) {
    [_, fullName, modifier] = lMatches;
    return [fullName, modifier];
  } else {
    return [undef, undef];
  }
};

// ---------------------------------------------------------------------------
setDebugging();
