// Generated by CoffeeScript 2.7.0
// exceptions.coffee
var EXLOG, doHaltOnError, doLog, lExceptionLog;

import {
  getV8Stack,
  nodeStr
} from '@jdeighan/base-utils/v8-stack';

import {
  undef,
  defined,
  notdefined
} from '@jdeighan/base-utils/utils';

doHaltOnError = false;

doLog = true;

// ---------------------------------------------------------------------------
export var suppressExceptionLogging = function() {
  doLog = false;
};

// ---------------------------------------------------------------------------
export var haltOnError = function(flag = true) {
  var save;
  // --- return existing setting
  save = doHaltOnError;
  doHaltOnError = flag;
  return save;
};

// ---------------------------------------------------------------------------
// simple redirect to an array - useful in unit tests
lExceptionLog = undef;

export var exReset = () => {
  lExceptionLog = [];
};

export var exGetLog = () => {
  var result;
  result = lExceptionLog.join("\n");
  lExceptionLog = undef;
  return result;
};

// ---------------------------------------------------------------------------
EXLOG = function(str) {
  if (lExceptionLog) {
    return lExceptionLog.push(str);
  } else if (doLog) {
    return console.log(str);
  }
};

// ---------------------------------------------------------------------------
//   assert - mimic nodejs's assert
//   return true so we can use it in boolean expressions
export var assert = function(cond, msg) {
  var i, lFrames, len, node;
  if (!cond) {
    lFrames = getV8Stack().slice(3);
    EXLOG('-------------------------');
    EXLOG('JavaScript CALL STACK:');
    for (i = 0, len = lFrames.length; i < len; i++) {
      node = lFrames[i];
      EXLOG(`   ${nodeStr(node)}`);
      if (node.type === 'script') {
        break;
      }
    }
    EXLOG('-------------------------');
    EXLOG(`ERROR: ${msg}`);
    croak(msg);
  }
  return true;
};

// ---------------------------------------------------------------------------
//   croak - throws an error after possibly printing useful info
//           err can be a string or an Error object
export var croak = function(err, label = undef, obj = undef) {
  var curmsg, newmsg;
  if ((typeof err === 'string') || (err instanceof String)) {
    curmsg = err;
  } else {
    curmsg = err.message;
  }
  if ((label === undef) || (label === null) || (label === '')) {
    newmsg = `ERROR (croak): ${curmsg}`;
  } else {
    newmsg = `ERROR (croak): ${curmsg}
${label}:
${JSON.stringify(obj)}`;
  }
  if (doHaltOnError) {
    EXLOG(newmsg);
    return process.exit();
  } else {
    // --- re-throw the error
    doLog = true; // reset for next error
    throw new Error(newmsg);
  }
};
