// Generated by CoffeeScript 2.7.0
  // prefix.coffee
import {
  strict as assert
} from 'node:assert';

import {
  undef,
  OL,
  setCharsAt
} from '@jdeighan/exceptions/utils';

// --- We use spaces here because Windows Terminal handles TAB chars badly
export var vbar = '│'; // unicode 2502

export var hbar = '─'; // unicode 2500

export var corner = '└'; // unicode 2514

export var arrowhead = '>';

export var space = ' ';

export var dot = '.';

export var fourSpaces = space + space + space + space;

export var oneIndent = vbar + space + space + space;

export var arrow = corner + hbar + arrowhead + space;

export var dotIndent = dot + space + space + space;

// ---------------------------------------------------------------------------
export var getPrefix = function(level, option = 'none') {
  if ((option === 'noLast2Vbars') && (level < 2)) {
    option = 'noLastVbar';
  }
  switch (option) {
    case 'plain':
      return oneIndent.repeat(level);
    case 'withArrow':
      if (level === 0) {
        return arrow;
      } else {
        return oneIndent.repeat(level - 1) + arrow;
      }
      break;
    case 'noLastVbar':
      assert(level >= 1, `getPrefix(), noLastVbar but level=${OL(level)}`);
      return oneIndent.repeat(level - 1) + fourSpaces;
    case 'noLast2Vbars':
      assert(level >= 2, `getPrefix(), noLast2Vbars but level=${OL(level)}`);
      return oneIndent.repeat(level - 2) + fourSpaces + fourSpaces;
    case 'dotLastVbar':
      assert(level >= 1, `getPrefix(), dotLastVbar but level=${OL(level)}`);
      return oneIndent.repeat(level - 1) + dotIndent;
    case 'dotLast2Vbars':
      assert(level >= 2, `getPrefix(), dotLast2Vbars but level=${OL(level)}`);
      return oneIndent.repeat(level - 2) + dotIndent + fourSpaces;
    default:
      return fourSpaces.repeat(level);
  }
};

// ---------------------------------------------------------------------------
export var addArrow = function(prefix) {
  var pos, result;
  pos = prefix.lastIndexOf(vbar);
  if (pos === -1) {
    result = prefix;
  } else {
    result = setCharsAt(prefix, pos, arrow);
  }
  return result;
};

// ---------------------------------------------------------------------------
export var removeLastVbar = function(prefix) {
  var pos, result;
  pos = prefix.lastIndexOf(vbar);
  if (pos === -1) {
    result = prefix;
  } else {
    result = setCharsAt(prefix, pos, ' ');
  }
  return result;
};
