// Generated by CoffeeScript 2.7.0
// taml.coffee
var myReplacer, squote;

import yaml from 'js-yaml';

import {
  strict as assert
} from 'node:assert';

import {
  undef,
  defined,
  notdefined,
  isEmpty,
  isString,
  isObject,
  blockToArray,
  arrayToBlock,
  hasChar,
  escapeStr,
  chomp,
  OL
} from '@jdeighan/exceptions/utils';

// ---------------------------------------------------------------------------
//   isTAML - is the string valid TAML?
export var isTAML = function(text) {
  return isString(text) && text.match(/^---$/m);
};

// ---------------------------------------------------------------------------
//   taml - convert valid TAML string to a JavaScript value
export var fromTAML = function(text) {
  var _, i, j, lLines, len, line, prefix, ref, str;
  assert(defined(text), "text is undef");
  assert(isTAML(text), `string ${OL(text)} isn't TAML`);
  // --- TAML uses TAB characters for indentation
  lLines = ['---'];
  ref = blockToArray(text);
  for (i = j = 0, len = ref.length; j < len; i = ++j) {
    line = ref[i];
    if (i === 0) {
      continue;
    }
    [_, prefix, str] = line.match(/^(\s*)(.*)$/);
    str = str.trim();
    assert(!hasChar(prefix, ' '), `space char in prefix: ${OL(line)}`);
    lLines.push(' '.repeat(prefix.length) + tamlFix(str));
  }
  return yaml.load(arrayToBlock(lLines), {
    skipInvalid: true
  });
};

// ---------------------------------------------------------------------------
export var tamlFix = (str) => {
  var _, key, lMatches, valStr;
  if (lMatches = str.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$/)) { // the key
    [_, key, valStr] = lMatches;
    if (isEmpty(valStr)) {
      return `${key}:`;
    } else {
      return `${key}: ${fixValStr(valStr)}`;
    }
  } else {
    return str;
  }
};

// ---------------------------------------------------------------------------
export var fixValStr = (valStr) => {
  if (isEmpty(valStr) || valStr.match(/^\d+(?:\.\d*)?$/) || valStr.match(/^\".*\"$/) || valStr.match(/^\'.*\'$/)) {
    return valStr;
  } else {
    return "'" + valStr.replace(/'/g, "''") + "'";
  }
};

// ---------------------------------------------------------------------------
// --- a replacer is (key, value) -> newvalue
myReplacer = function(name, value) {
  if (value === undef) {
    // --- We need this, otherwise js-yaml will convert undef to null
    return "<UNDEFINED_VALUE>";
  }
  if (isString(value)) {
    return escapeStr(value);
  } else {
    //	else if isObject(value, ['tamlReplacer'])
    //		return value.tamlReplacer()
    return value;
  }
};

// ---------------------------------------------------------------------------
export var toTAML = function(obj, hOptions = {
    sortKeys: true
  }) {
  var escape, replacer, sortKeys, str, useTabs;
  if (obj === undef) {
    return "---\nundef";
  }
  if (obj === null) {
    return "---\nnull";
  }
  ({useTabs, sortKeys, escape, replacer} = hOptions);
  if (notdefined(replacer)) {
    replacer = myReplacer;
  }
  str = yaml.dump(obj, {
    skipInvalid: true,
    indent: 3,
    sortKeys: !!sortKeys,
    lineWidth: -1,
    replacer
  });
  str = str.replace(/<UNDEFINED_VALUE>/g, 'undef');
  if (useTabs) {
    str = str.replace(/   /g, "\t");
  }
  return "---\n" + chomp(str);
};

// ---------------------------------------------------------------------------
squote = function(text) {
  return "'" + text.replace(/'/g, "''") + "'";
};
