// Generated by CoffeeScript 2.7.0
// utils.coffee
var myReplacer;

import {
  strict as assert
} from 'node:assert';

export const undef = void 0;

// ---------------------------------------------------------------------------
//   pass - do nothing
export var pass = () => {
  return true;
};

// ---------------------------------------------------------------------------
export var defined = (obj) => {
  return (obj !== undef) && (obj !== null);
};

// ---------------------------------------------------------------------------
export var notdefined = (obj) => {
  return (obj === undef) || (obj === null);
};

// ---------------------------------------------------------------------------
export var untabify = (str, numSpaces = 3) => {
  return str.replace(/\t/g, ' '.repeat(numSpaces));
};

// ---------------------------------------------------------------------------
//   deepCopy - deep copy an array or object
export var deepCopy = function(obj) {
  var err, newObj, objStr;
  if (obj === undef) {
    return undef;
  }
  objStr = JSON.stringify(obj);
  try {
    newObj = JSON.parse(objStr);
  } catch (error) {
    err = error;
    croak("ERROR: err.message", objStr);
  }
  return newObj;
};

// ---------------------------------------------------------------------------
// --- a replacer is (key, value) -> newvalue
myReplacer = function(name, value) {
  if (value === undef) {
    return 'undef';
  } else if (value === null) {
    return null;
  } else if (isString(value)) {
    return escapeStr(value);
  } else if (isObject(value, ['tamlReplacer'])) {
    return value.tamlReplacer();
  } else {
    return value;
  }
};

// ---------------------------------------------------------------------------
export var OL = function(obj) {
  if (defined(obj)) {
    if (isString(obj)) {
      return quoted(obj, 'escape');
    } else {
      //			return "'#{escapeStr(obj)}'"
      return JSON.stringify(obj);
    }
  } else if (obj === null) {
    return 'null';
  } else {
    return 'undef';
  }
};

// ---------------------------------------------------------------------------
export var quoted = (str, escape = undef) => {
  assert(isString(str), "not a string");
  switch (escape) {
    case 'escape':
      str = escapeStr(str);
      break;
    case 'escapeNoNL':
      str = escapeStr(str, hEscNoNL);
      break;
    default:
      pass;
  }
  if (!hasChar(str, "'")) {
    return "'" + str + "'";
  }
  if (!hasChar(str, '"')) {
    return '"' + str + '"';
  }
  return '<' + str + '>';
};

// ---------------------------------------------------------------------------
//   escapeStr - escape newlines, TAB chars, etc.
export var hEsc = {
  "\n": '®',
  "\t": '→',
  " ": '˳'
};

export var hEscNoNL = {
  "\t": '→',
  " ": '˳'
};

export var escapeStr = function(str, hReplace = hEsc) {
  var ch, lParts;
  assert(isString(str), "escapeStr(): not a string");
  lParts = (function() {
    var i, len1, ref, results;
    ref = str.split('');
    results = [];
    for (i = 0, len1 = ref.length; i < len1; i++) {
      ch = ref[i];
      if (defined(hReplace[ch])) {
        results.push(hReplace[ch]);
      } else {
        results.push(ch);
      }
    }
    return results;
  })();
  return lParts.join('');
};

// ---------------------------------------------------------------------------
export var hasChar = (str, ch) => {
  return str.indexOf(ch) >= 0;
};

// ---------------------------------------------------------------------------
//   unescapeStr - unescape newlines, TAB chars, etc.
export var hUnesc = {
  '®': "\n",
  '→': "\t",
  '˳': " "
};

export var unescapeStr = function(str, hReplace = hUnesc) {
  return escapeStr(str, hReplace);
};

// ---------------------------------------------------------------------------
export var isString = (x) => {
  return (typeof x === 'string') || (x instanceof String);
};

// ---------------------------------------------------------------------------
export var isNumber = function(x, hOptions = undef) {
  var max, min, result;
  result = (typeof x === 'number') || (x instanceof Number);
  if (result && defined(hOptions)) {
    if (!isHash(hOptions)) {
      LOG(`2nd arg not a hash: ${OL(hOptions)}`);
      process.exit();
    }
    ({min, max} = hOptions);
    if (defined(min) && (x < min)) {
      result = false;
    }
    if (defined(max) && (x > max)) {
      result = false;
    }
  }
  return result;
};

// ---------------------------------------------------------------------------
export var isInteger = function(x, hOptions = {}) {
  var result;
  if (typeof x === 'number') {
    result = Number.isInteger(x);
  } else if (x instanceof Number) {
    result = Number.isInteger(x.valueOf());
  } else {
    result = false;
  }
  if (result) {
    if (defined(hOptions.min) && (x < hOptions.min)) {
      result = false;
    }
    if (defined(hOptions.max) && (x > hOptions.max)) {
      result = false;
    }
  }
  return result;
};

// ---------------------------------------------------------------------------
export var getClassName = function(obj) {
  if (typeof obj !== 'object') {
    return undef;
  }
  return obj.constructor.name;
};

// ---------------------------------------------------------------------------
export var isHash = function(x, lKeys) {
  var i, key, len1;
  if (!x || (getClassName(x) !== 'Object')) {
    return false;
  }
  if (defined(lKeys)) {
    if (!isArray(lKeys)) {
      LOG("isHash(): lKeys not an array");
      process.exit();
    }
    for (i = 0, len1 = lKeys.length; i < len1; i++) {
      key = lKeys[i];
      if (!x.hasOwnProperty(key)) {
        return false;
      }
    }
  }
  return true;
};

// ---------------------------------------------------------------------------
export var isArray = function(x) {
  return Array.isArray(x);
};

// ---------------------------------------------------------------------------
export var isBoolean = function(x) {
  return typeof x === 'boolean';
};

// ---------------------------------------------------------------------------
export var isConstructor = function(f) {
  var err;
  try {
    new f();
  } catch (error) {
    err = error;
    if (err.message.indexOf('is not a constructor') >= 0) {
      return false;
    }
  }
  return true;
};

// ---------------------------------------------------------------------------
export var isFunction = function(x) {
  return typeof x === 'function';
};

// ---------------------------------------------------------------------------
export var isRegExp = function(x) {
  return x instanceof RegExp;
};

// ---------------------------------------------------------------------------
export var isObject = function(x, lReqKeys = undef) {
  var i, key, len1, result;
  result = (typeof x === 'object') && !isString(x) && !isArray(x) && !isHash(x) && !isNumber(x);
  if (result) {
    if (defined(lReqKeys)) {
      if (!isArray(lReqKeys)) {
        LOG("lReqKeys is not an array");
        process.exit();
      }
      for (i = 0, len1 = lReqKeys.length; i < len1; i++) {
        key = lReqKeys[i];
        if (!x.hasOwnProperty(key)) {
          return false;
        }
      }
    }
    return true;
  } else {
    return false;
  }
};

// ---------------------------------------------------------------------------
export var hasMethod = (obj, name) => {
  assert(isObject(obj), "not an object");
  assert(isString(name), "name is not a string");
  return typeof obj[name] === 'function';
};

// ---------------------------------------------------------------------------
export var jsType = function(x) {
  var lKeys;
  if (x === null) {
    return [undef, 'null'];
  } else if (x === undef) {
    return [undef, 'undef'];
  } else if (isString(x)) {
    if (x.match(/^\s*$/)) {
      return ['string', 'empty'];
    } else {
      return ['string', undef];
    }
  } else if (isNumber(x)) {
    if (Number.isInteger(x)) {
      return ['number', 'integer'];
    } else {
      return ['number', undef];
    }
  } else if (isBoolean(x)) {
    if (x) {
      return ['boolean', 'true'];
    } else {
      return ['boolean', 'false'];
    }
  } else if (isHash(x)) {
    lKeys = Object.keys(x);
    if (lKeys.length === 0) {
      return ['hash', 'empty'];
    } else {
      return ['hash', undef];
    }
  } else if (isArray(x)) {
    if (x.length === 0) {
      return ['array', 'empty'];
    } else {
      return ['array', undef];
    }
  } else if (isRegExp(x)) {
    return ['regexp', undef];
  } else if (isConstructor(x)) {
    return ['function', 'constructor'];
  } else if (isFunction(x)) {
    return ['function', undef];
  } else if (isObject(x)) {
    return ['object', undef];
  } else {
    throw new Error(`Unknown type: ${OL(x)}`);
  }
};

// ---------------------------------------------------------------------------
//   isEmpty
//      - string is whitespace, array has no elements, hash has no keys
export var isEmpty = function(x) {
  if ((x === undef) || (x === null)) {
    return true;
  }
  if (isString(x)) {
    return x.match(/^\s*$/);
  }
  if (isArray(x)) {
    return x.length === 0;
  }
  if (isHash(x)) {
    return Object.keys(x).length === 0;
  } else {
    return false;
  }
};

// ---------------------------------------------------------------------------
//   nonEmpty
//      - string has non-whitespace, array has elements, hash has keys
export var nonEmpty = function(x) {
  if (x == null) {
    return false;
  }
  if (isString(x)) {
    return !x.match(/^\s*$/);
  }
  if (isArray(x)) {
    return x.length > 0;
  }
  if (isHash(x)) {
    return Object.keys(x).length > 0;
  } else {
    return defined(x);
  }
};

// ---------------------------------------------------------------------------
//   blockToArray - split a block into lines
export var blockToArray = function(block) {
  var lLines, len;
  if ((block === undef) || (block === '')) {
    return [];
  } else {
    assert(isString(block), `block is ${jsType(block)}`);
    lLines = block.split(/\r?\n/);
    // --- remove trailing empty lines
    len = lLines.length;
    while ((len > 0) && isEmpty(lLines[len - 1])) {
      lLines.pop();
      len -= 1;
    }
    return lLines;
  }
};

// ---------------------------------------------------------------------------
//   arrayToBlock - block and lines in block will have no trailing whitespace
export var arrayToBlock = function(lLines, hEsc = undef) {
  var result;
  if (lLines === undef) {
    return undef;
  }
  assert(isArray(lLines), "lLines is not an array");
  lLines = lLines.filter((line) => {
    return defined(line);
  });
  if (lLines.length === 0) {
    return undef;
  } else {
    result = rtrim(lLines.join('\n'));
    if (defined(hEsc)) {
      result = escapeStr(result, hEsc);
    }
    return result;
  }
};

// ---------------------------------------------------------------------------
export var chomp = function(str) {
  var len, tail;
  len = str.length;
  if (len === 0) {
    return '';
  } else if (len === 1) {
    if ((str === "\r") || (str === "\n")) {
      return '';
    } else {
      return str;
    }
  } else {
    // --- check the last 2 characters
    tail = str.substring(len - 2);
    if (tail === "\r\n") {
      return str.substring(0, len - 2);
    } else {
      tail = str.substring(len - 1);
      if (tail === "\n") {
        return str.substring(0, len - 1);
      } else {
        return str;
      }
    }
  }
};

// ---------------------------------------------------------------------------
//   rtrim - strip trailing whitespace
export var rtrim = function(line) {
  var lMatches, n;
  assert(isString(line), "rtrim(): line is not a string");
  lMatches = line.match(/\s+$/);
  if (lMatches != null) {
    n = lMatches[0].length; // num chars to remove
    return line.substring(0, line.length - n);
  } else {
    return line;
  }
};

// ---------------------------------------------------------------------------
export var setCharsAt = function(str, pos, str2) {
  assert(pos >= 0, `negative pos ${pos} not allowed`);
  assert(pos < str.length, `pos ${pos} not in ${OL(str)}`);
  if (pos + str2.length >= str.length) {
    return str.substring(0, pos) + str2;
  } else {
    return str.substring(0, pos) + str2 + str.substring(pos + str2.length);
  }
};

// ---------------------------------------------------------------------------
export var words = function(str) {
  str = str.trim();
  if (str === '') {
    return [];
  }
  return str.split(/\s+/);
};
